"""add defaults to users timestamps

Revision ID: 0414706b5228
Revises: 18176a12e9fd
Create Date: 2026-01-01 14:27:00.633633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0414706b5228'
down_revision: Union[str, None] = '18176a12e9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
    "users",
    "created_at",
    server_default=sa.func.now(),
    nullable=False,
)

op.alter_column(
    "users",
    "updated_at",
    server_default=sa.func.now(),
    nullable=False,
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
