"""Add scrape_jobs table

Revision ID: b8109a129bc6
Revises: 0414706b5228
Create Date: 2026-01-12 12:25:30.291844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8109a129bc6'
down_revision: Union[str, None] = '0414706b5228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.Enum('PROFILE', 'POST', name='scrapejobtype'), nullable=False),
    sa.Column('entity_key', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('GOOGLE', 'FOLLOWUP', 'MANUAL', name='scrapejobsource'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'RATE_LIMITED', 'FAILED', 'DEAD', name='scrapejobstatus'), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type', 'entity_key', name='uq_scrape_jobs_job_type_entity_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###
