"""Tables

Revision ID: d1a657c2021a
Revises: f5a955453f0e
Create Date: 2026-01-01 12:57:11.324318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a657c2021a'
down_revision: Union[str, None] = 'f5a955453f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_metadata',
    sa.Column('shortcode', sa.String(length=32), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('posted_on', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('content_kind', sa.String(length=16), nullable=False),
    sa.Column('is_container', sa.Boolean(), nullable=False),
    sa.Column('collaborators', sa.Text(), nullable=False),
    sa.Column('scraped_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("(content_kind = 'reel' AND is_container = FALSE) OR (content_kind = 'post')", name='ck_posts_container_validity'),
    sa.CheckConstraint("content_kind IN ('post','reel')", name='ck_posts_content_kind'),
    sa.PrimaryKeyConstraint('shortcode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('bio_text', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('profile_url', sa.String(length=255), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(username) > 0', name='ck_users_username_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_shortcode', sa.String(length=32), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('media_subtype', sa.Integer(), nullable=True),
    sa.Column('media_index', sa.Integer(), nullable=False),
    sa.Column('tagged_users', sa.Text(), nullable=False),
    sa.Column('scraped_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("media_type IN ('image','video')", name='ck_media_type'),
    sa.ForeignKeyConstraint(['post_shortcode'], ['posts_metadata.shortcode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_shortcode', 'media_index', name='uq_post_media_index')
    )
    op.create_table('user_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('link_type', sa.String(length=100), nullable=True),
    sa.Column('extracted_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(url) > 0', name='ck_user_links_url_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_user_links_user_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_links')
    op.drop_table('post_media')
    op.drop_table('users')
    op.drop_table('posts_metadata')
    # ### end Alembic commands ###
